### ISSUE TITLE
Voxel-Commands extensions

### ISSUE THREAD

**Issue by z3t0** [voxel/ideas#43]
Add support for each plugin to provide commands for https://github.com/voxel/voxel-commands

**Comment by deathcap** [comment]
I thought plugins can already register commands, but would need to double-check to be sure (was it through voxel-commands or voxel-console?)

**Comment by z3t0** [comment]
> I thought plugins can already register commands

Sorry didnt know that...
One good idea would be to document the plugin creation system, maybe create a basic plugin template?

**Comment by z3t0** [comment]
my bad, https://github.com/voxel/voxel-commands does support plugins registering their own commands
